### ISSUE TITLE
Spacerace game error?

### ISSUE THREAD

**Issue by sangjunp4rk** [codephil-columbia/typephil#104]

**Comment by sangjunp4rk** [comment]
Not sure if this bug was fixed in the newer challenge_space_merge branch iliana was working on

![image](https://user-images.githubusercontent.com/16650063/59545797-16f69780-8ef2-11e9-8271-c26d026b5df7.png)

![image](https://user-images.githubusercontent.com/16650063/59545802-2d9cee80-8ef2-11e9-9dd7-ea057af729de.png)

![image](https://user-images.githubusercontent.com/16650063/59545803-3097df00-8ef2-11e9-8c2a-cf156464bc70.png)

**Comment by mattvanegas13** [comment]
i dont think it does - this happens because of a fetch request on lines 196 in the file in the offline branch. This was removed in iliana's branch
