### ISSUE TITLE
Get Chapter 2.svg graphics

### ISSUE THREAD

**Issue by sangjunp4rk** [codephil-columbia/typephil#110]
chapter 2.svg graphics is missing. need to ask chelsy for it and upload and add. current version is a .png

![image](https://user-images.githubusercontent.com/16650063/59733170-f3498f00-921a-11e9-8f43-cb666d81eea1.png)

**Comment by sangjunp4rk** [comment]
![image](https://user-images.githubusercontent.com/16650063/59733878-5c320680-921d-11e9-8e86-b51fdb39207c.png)

**Comment by francesar** [comment]
any updates on this @sangjunp4rk

**Comment by sangjunp4rk** [comment]
No word yet i'm trying to get a hold of chelsy
