### ISSUE TITLE
Spacerace kill all instances when you switch page

### ISSUE THREAD

**Issue by sangjunp4rk** [codephil-columbia/typephil#111]
Currently, when you start playing the spacerace game and then you exist (like press home), it throws you an error because it keeps trying to append to something that doesn't exist. we need to kill all instances when we exist the page...

![image](https://user-images.githubusercontent.com/16650063/59851584-fdfb4580-933a-11e9-8a26-4ba1f9cce07a.png)

**Comment by francesar** [comment]
Gonna close this one, since its the same as the other kill instance thing that should already be fixed
