### ISSUE TITLE
Boatgame + Challenge + Exam + Tutorial (when you are typing) kill all instances

### ISSUE THREAD

**Issue by sangjunp4rk** [codephil-columbia/typephil#112]
Same issue as spacerace. when you logout after you start the game, the app crashses because it's searching for something that no longer exists i think. we need to kill all instances when we exit

![image](https://user-images.githubusercontent.com/16650063/59852101-246db080-933c-11e9-84ad-5288660c8e2a.png)

**Comment by sangjunp4rk** [comment]
Seems to only be a problem when you logout after the game starts. doesn't throw the error in other cases like redirecting to the home page or learn page

to reproduce start playing the game then log out. make sure you pull my latest changes that add logout functionality

**Comment by sangjunp4rk** [comment]
Error with Tutorial. It seems to be because it's all based on the same foundatinoal code?

![image](https://user-images.githubusercontent.com/16650063/59860229-4ec76a00-934c-11e9-800b-ca5f721505e3.png)

**Comment by sangjunp4rk** [comment]
*** Only happens when you log out midway. not if you redirect to another page within the page after you log in

**Comment by francesar** [comment]
I think it has to do with [this](https://github.com/codephil-columbia/typephil/blob/4a5c19624844721423287e8d0099bc2b2eb877ef/src/components/TutorialContent.js#L312) not being removed when the component gets unmounted

**Comment by francesar** [comment]
if this issue comes up again reopen this issue, but for now im gonna close this

**Comment by sangjunp4rk** [comment]
Still running into this problem for the /exam. To recreate, navigate to the exam page (next to the logout option in the navbar). Select a test and start typing. then log out half way. For some reason it doesn't trigger every time. i tried look at your commit https://github.com/codephil-columbia/typephil/commit/e9d629864be31c5d71890ed2bc9f4c42424fb114 but i couldn't find where to edit lol

![image](https://user-images.githubusercontent.com/16650063/60116605-3b8e1300-972d-11e9-9128-d62102a91b45.png)

**Comment by sangjunp4rk** [comment]
Can you also double check you fix the problem for tutorial? i ran into the problem once but can't recreate it... :O

**Comment by sangjunp4rk** [comment]
But it seems to be a delayed action. Like the error page pops up after like a minute or so.

![image](https://user-images.githubusercontent.com/16650063/60117016-19e15b80-972e-11e9-811e-cb7a93417e91.png)

**Comment by francesar** [comment]
> But it seems to be a delayed action. Like the error page pops up after like a minute or so.
> 
> ![image](https://user-images.githubusercontent.com/16650063/60117016-19e15b80-972e-11e9-811e-cb7a93417e91.png)

Can you look into recreating this same thing, specifically for Tutorial? The exam page didn't get the fix that I wrote for the other pages so it should be good now. But unsure why it is still throwing an error for the Tutorial

**Comment by francesar** [comment]
bump

**Comment by sangjunp4rk** [comment]
I found out what triggers it. When you start a tutorial and then log out half way and then in the sign-in page you click the down arrow (or any arrow, I used the down arrow to select my username), it triggers this indexOf undefined error.

![image](https://user-images.githubusercontent.com/16650063/60542359-99d86a00-9cc8-11e9-8850-078168ce645d.png)

**Comment by sangjunp4rk** [comment]
I'm just gonna check for "underfined" and return if it is is that fine.

**Comment by sangjunp4rk** [comment]
That seemed to fix it. I'm gonna close it but if you think this will cause larger problems let's reopen it
