### ISSUE TITLE
' and " are not registering in the Tutorial

### ISSUE THREAD

**Issue by sangjunp4rk** [codephil-columbia/typephil#114]
comma and apostrphies are not registering in the tutorial

![image](https://user-images.githubusercontent.com/16650063/60117319-b6a3f900-972e-11e9-9b00-dcd1399d0b62.png)

**Comment by francesar** [comment]
They aren't registering because the JSON file with lessons doesn't have them. Do you mind double checking that all the characters that you want are in this file [here](https://github.com/codephil-columbia/typephil/blob/offline/src/services/tutorialLessons.js)
