### ISSUE TITLE
Shuffle sentences that appear in challenge.

### ISSUE THREAD

**Issue by sangjunp4rk** [codephil-columbia/typephil#116]
currently displays sentences in the same order each time

**Comment by mattvanegas13** [comment]
@sangjunp4rk this code already exists in challenge_space_merge branch - i think you should be able to merge it

**Comment by francesar** [comment]
do u have a commit you can refer to? @sangjunp4rk @mattvanegas13

**Comment by sangjunp4rk** [comment]
dc35965b6ed245bc7fedf9159b4f00d8398061d5
