### ISSUE TITLE
If you redo a lesson, the scores don't update

### ISSUE THREAD

**Issue by sangjunp4rk** [codephil-columbia/typephil#117]
On superuser, i redid the chapter 1, lesson 3 but scores did not reupdate

![image](https://user-images.githubusercontent.com/16650063/60293237-b2fda700-98d3-11e9-90b0-534b335d6b30.png)

**Comment by francesar** [comment]
double check that it is fixed and close @sangjunp4rk

**Comment by sangjunp4rk** [comment]
brillo
