### ISSUE TITLE
Spacerace doesn't close properly

### ISSUE THREAD

**Issue by sangjunp4rk** [codephil-columbia/typephil#119]
Happens when you play the game then log out halfway. doesn't seem to be clearing everything when you exit. i think it is similar to the other problems we had about not clearing

![image](https://user-images.githubusercontent.com/16650063/60918943-7da57180-a262-11e9-9d15-deacfe75adf9.png)

**Comment by mattvanegas13** [comment]
@sangjunp4rk think its good - let me know if there's other instances of this

**Comment by sangjunp4rk** [comment]
nice job! it looks good
