### ISSUE TITLE
Sometimes tutorial gets stuck and can't progress

### ISSUE THREAD

**Issue by sangjunp4rk** [codephil-columbia/typephil#30]
Steps to reproduce: Start any lessons. In my case user as sangjun1, password was 123. I chose chapter 0, lesson 3 from learn page. Keep pressing next. Sometimes, if you click next, you get redirected to 404 page.

Seems to be persisting issue for chapter 0.

![image](https://user-images.githubusercontent.com/16650063/43556571-3ebce652-95b5-11e8-8b1e-99d18356e9e8.png)

![image](https://user-images.githubusercontent.com/16650063/43557021-7c80afb2-95b7-11e8-9e9a-9bb29cf0badf.png)

**Comment by francesar** [comment]
I think #40 covers this as well, which we already merged a fix for
