### ISSUE TITLE
No start next lesson option in learn

### ISSUE THREAD

**Issue by sangjunp4rk** [codephil-columbia/typephil#36]
Steps to reproduce: Click on next available lesson that you haven't started yet. Just add button and sangjun can do ui styling.

![image](https://user-images.githubusercontent.com/16650063/43556960-1e40476e-95b7-11e8-9a59-0fd5f48121e8.png)

**Comment by sangjunp4rk** [comment]
if you add just a basic button w functionality i can fix the ui

**Comment by francesar** [comment]
can you let me know what user you're using? Unsure if its a be/fe issue
