### ISSUE TITLE
Add Https 

### ISSUE THREAD

**Issue by francesar** [codephil-columbia/typephil#39]

**Comment by NWChen** [comment]
blocked by AWS case for failing SSH:
https://console.aws.amazon.com/support/v1#/case/?displayId=5289279031&language=en

**Comment by NWChen** [comment]
force HTTP on `typephil.org` and `api.typephil.org` to redirect to HTTPS both

s/o to @francesar for setting up `certbot` and Vinay S. at AWS Support
