### ISSUE TITLE
When you click "restart" after low accuracy, you are redirected to beginning of Chapter

### ISSUE THREAD

**Issue by sangjunp4rk** [codephil-columbia/typephil#41]
When you click "restart" after low accuracy, you are redirected to beginning of chapter instead of just redoing the exercise. (It shouldn't redirect to the beginning of the lesson either, just the exercise).

Steps to reproduce: sangjun1, 123. Navigate to chapter 1, lesson 2. Then fail the first exercise. Then click restart. You will be redirected to chapter 1, lesson 1.

![image](https://user-images.githubusercontent.com/16650063/43691014-b6254e0c-98c9-11e8-89c4-acd4d9a993e7.png)

->

![image](https://user-images.githubusercontent.com/16650063/43691016-bc7b8960-98c9-11e8-8810-fda7a9afaba3.png)

**Comment by NWChen** [comment]
https://github.com/codephil-columbia/typephil/commit/c0a42d8c013c8e08575b4551440d0c83061573ed
