### ISSUE TITLE
Trim Error?

### ISSUE THREAD

**Issue by sangjunp4rk** [codephil-columbia/typephil#59]
Steps to reproduce: tester91, 123. Seems to happen only if you use the keyboard arrows to progress through the end of lesson. So when you click the keyboard arrow for the last page on the lesson, it becomes like this.  

![image](https://user-images.githubusercontent.com/16650063/44258304-1abd7d00-a241-11e8-9003-1a96a18fc8c7.png)

![image](https://user-images.githubusercontent.com/16650063/44258330-2c068980-a241-11e8-8612-e86776692b4a.png)

**Comment by NWChen** [comment]
duplicate prev/next button logic - [the commit](https://github.com/codephil-columbia/typephil/commit/a0b90d81a3c36ddd8d13c9e2050f155ece8cbc3b)

**Comment by NWChen** [comment]
still broken

**Comment by NWChen** [comment]
duplicate lesson finish logic. [(commit)](https://github.com/codephil-columbia/typephil/commit/5a2ca77f431fec74c103cd1d244a6d55444e1449)
