### ISSUE TITLE
Tutorial gets stuck when restarting old lessons from Learn page

### ISSUE THREAD

**Issue by sangjunp4rk** [codephil-columbia/typephil#83]
Tutorial lesson cannot progress onto the next lesson when restarting already completed lessons from the Learn page. For example, I completed chapter 0, lesson 3 and then also completed chapter 0, lesson 4. I exit. Then I go to the Learn page and click on chapter 0, lesson 3. I do the lesson again but at the end I cannot move onto next lesson.

So there are cases where you don't complete a lesson (the furthest out lesson so you haven't done any lessons after this lesson) and you exit. You can't progress to the next lesson if you start off again from the Learn page. The only way you can progress is if you press "Start" from the Homepage.

User: tester128, 123

**Error that occurs. It sends action "POST_TUTORIAL_SUCCESS" but doesn't do anything with it**
![image](https://user-images.githubusercontent.com/16650063/51874597-a2023700-232f-11e9-8499-95569962184e.png)

**Comment by francesar** [comment]
do u mind also including the logged in user info (username + password)
