### ISSUE TITLE
SQL: No Rows in Result Set

### ISSUE THREAD

**Issue by Ray725** [codephil-columbia/typephil#85]
I don't know why this started happening but nothing will load. Have tried recloning and rerunning both repositories several times.

![50411483_2295378160475101_5194901994078208000_n](https://user-images.githubusercontent.com/13423095/52158303-f295cf00-2664-11e9-9bf1-a4cac8c1da6d.png)
![51018187_2419793111426631_1842516746368450560_n](https://user-images.githubusercontent.com/13423095/52158304-f6295600-2664-11e9-9d1a-9d4c2619d1dc.png)
![50485330_2229251110459188_1619466338634301440_n](https://user-images.githubusercontent.com/13423095/52158307-f88bb000-2664-11e9-8204-a5829a83814e.png)

**Comment by NWChen** [comment]
looking
