### ISSUE TITLE
Ability to start the first lesson of each chapter

### ISSUE THREAD

**Issue by sangjunp4rk** [codephil-columbia/typephil#96]
- Ability to start the first lesson from every chapter. This way a more advanced user doesn’t have to start all the way from the beginning or if a user forget his/her password and just created a new account he/she doesn’t have to start again from the start.

**Comment by francesar** [comment]
how do u resolve what lesson a user is on if it's not sequential anymore? If they forgot their password it makes more sense for us to have something that allows them to recover a password. I will also make the point that we might have some "advanced" users that still type with bad habits, which is supposed to be taught in the first few chapters. 
I agree that we should figure out how to appeal to advanced users but I don't think this is the best way to do so.

@mattvanegas13 @ilianac feel free to chime in before we make a decision

**Comment by sangjunp4rk** [comment]
I guess it's fine to leave it as is. since we got rid of the timer in the tutorial they can just blaze through if necessary
