### ISSUE TITLE
Tutorial redirecting

### ISSUE THREAD

**Issue by sangjunp4rk** [codephil-columbia/typephil#97]
- When you finish a lesson/chapter, you are always redirected back to the learn homepage. Use should just be able to continue onto the next one

**Comment by francesar** [comment]
💀

**Comment by sangjunp4rk** [comment]
lol what does that mean

**Comment by francesar** [comment]
lol its just a pain to implement, but working on it rn

**Comment by francesar** [comment]
someone double check this before closing ya :)

**Comment by sangjunp4rk** [comment]
looking gooood
