### ISSUE TITLE
Back arrow disappears for tutorial 

### ISSUE THREAD

**Issue by sangjunp4rk** [codephil-columbia/typephil#98]
- At the end of a chapter/lesson, the back arrow disappears. We should always show the back arrow. 

![image](https://user-images.githubusercontent.com/16650063/59508503-3226c000-8e7c-11e9-9049-ef4bc8871e52.png)

**Comment by francesar** [comment]
fixed in offline branch, close once u double check

**Comment by sangjunp4rk** [comment]
nice
