### ISSUE TITLE
Profiles page breaks

### ISSUE THREAD

**Issue by sangjunp4rk** [codephil-columbia/typephil#99]
-  Profiles page breaks for me
![image](https://user-images.githubusercontent.com/16650063/59508522-423e9f80-8e7c-11e9-86ea-a073ffcf261f.png)
![image](https://user-images.githubusercontent.com/16650063/59508528-44a0f980-8e7c-11e9-9ad2-f1e1c9e287ef.png)

**Comment by francesar** [comment]
its not implemented yet for offline

**Comment by francesar** [comment]
fixed on the offline branch
